livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.server.spark-home = /opt/spark
livy.spark.master = spark://spark-master:7077
livy.spark.deploy-mode = client
livy.file.local-dir-whitelist = /opt/iceberg-ops/jobs
livy.repl.enable-hive-context = false
livy.server.recovery.mode = off
livy.server.session.state-retain.sec = 3600s
livy.server.csrf-protection.enabled = false
